# Authentication Service Configuration
# This file contains configuration options for the generic authentication service

# Server configuration
server:
  port: 8080
  servlet:
    context-path: /

# Spring configuration
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:h2:mem:authdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      host: localhost
      port: 6379

# Security configuration
security:
  jwt:
    secret: ${JWT_SECRET:your-secret-key-should-be-at-least-32-chars-long}
    access-token-validity-seconds: 3600
    refresh-token-validity-seconds: 86400
    token-type: Bearer

# API configuration
api:
  # Authentication endpoints configuration
  auth:
    base-path: /api/auth
    register-path: /register
    login-path: /login
    token-type: Bearer

  # Token endpoints configuration
  token:
    base-path: /api/token
    refresh-path: /refresh

  # API documentation configuration
  docs:
    title: Authentication Service API
    description: API documentation for the authentication service
    version: 1.0
    contact:
      name: Support Team
      email: support@example.com

# Email configuration
email:
  host: ${EMAIL_HOST:smtp.example.com}
  port: ${EMAIL_PORT:587}
  username: ${EMAIL_USERNAME:your-email@example.com}
  password: ${EMAIL_PASSWORD:your-password}
  protocol: smtp
  auth: true
  starttls: true
  debug: false

# Notification configuration
notification:
  email:
    enabled: ${EMAIL_ENABLED:true}
    from: ${EMAIL_FROM:noreply@example.com}
    welcome:
      subject: Welcome to the Authentication Service
    password-change:
      subject: Your password has been changed
    password-reset:
      subject: Password Reset Request
    account-status:
      subject: Account Status Update
    login:
      subject: New Login Detected
    security-alert:
      subject: Security Alert

# Logging configuration
logging:
  level:
    root: INFO
    com.unik.auth: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
